In [76]:
# author: Vladimir Osin 

## NumPy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. 
This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

**Note:** NumPy stands for Numeric Python. It's easy, fast and allow calculations over entire arrays. Find more [here](http://www.numpy.org/) 

## Basic usage

In [77]:
# let's import library first
import numpy as np

In [78]:
# from Python list to Numpy array
python_list = [1.2, 3.4, 6, 99]
np_array = np.array(python_list)
print(np_array)

[ 1.2  3.4  6.  99. ]


In [79]:
# add/substract/divide/multiply by scalar
np_array+4.5, np_array-4.5, np_array/4.5, np_array*4.5 

(array([  5.7,   7.9,  10.5, 103.5]),
 array([-3.3, -1.1,  1.5, 94.5]),
 array([ 0.26666667,  0.75555556,  1.33333333, 22.        ]),
 array([  5.4,  15.3,  27. , 445.5]))

In [80]:
# subsetting
np_array[np_array<3]

array([1.2])

In [81]:
# shape of array
print(np_array.shape) # column vector

(4,)


## Basic Statistics 

In [82]:
# let's generate some data
data_points = np.random.randint(200, size=100)

In [83]:
data_points

array([196, 135, 113,  70, 151, 198, 174,  71, 111, 111, 179, 153, 167,
       188,  70,   7,  86,  69,  81, 158, 135,  41,  98,  91, 101, 120,
       157,  88,  66, 157,   7,  86,  88, 140, 116, 108, 139,  27, 110,
       141, 101, 148, 182,  94,  50,  92, 168,   9, 172, 125, 152, 140,
       166, 193,  73, 100, 153,  64, 151, 166, 131,  77, 159,  21, 135,
       177, 141,  16,  38,  83,  58, 199,  89, 188,  39, 136,  35, 104,
       104,  88, 137, 158, 128,  75, 145,  52,  22,  59, 147, 161, 165,
         1,   3, 171,  59, 150, 165, 153, 195,  44])

In [84]:
np.mean(data_points), np.median(data_points), np.std(data_points), np.max(data_points), np.min(data_points)

(112.11, 114.5, 52.85809209572361, 199, 1)

## Matrices (2D Arrays)

In [85]:
# 2D array
np_array2D = np.array([[1,2,3], [3,2,1], [5,6,2]])
print(f'Our 2D array: \n {np_array2D}')
print(f'\nShape of 2D array is {np_array2D.shape}') # matrix

# slice 2D array
np_array2D_sliced = np_array2D[1:, :-1]
print(f'\nOur 2D array (first row and last column sliced): \n {np_array2D_sliced}')

Our 2D array: 
 [[1 2 3]
 [3 2 1]
 [5 6 2]]

Shape of 2D array is (3, 3)

Our 2D array (first row and last column sliced): 
 [[3 2]
 [5 6]]


In [86]:
# matrix multiplication 
A = np.random.randint(25, size=(3,3))
B = np.random.randint(45, size=(3,3))

print(f'A matrix : \n {A}')
print(f'\nB matrix : \n {B}')
print(f'\nA*B element-wise: \n {A*B}')
print(f'\nA*B matrix multiplication : \n {A.dot(B)}')

A matrix : 
 [[ 0  1 23]
 [ 3  0 23]
 [ 5 24  5]]

B matrix : 
 [[34 17 19]
 [ 9  4 15]
 [35 42 28]]

A*B element-wise: 
 [[   0   17  437]
 [  27    0  345]
 [ 175 1008  140]]

A*B matrix multiplication : 
 [[ 814  970  659]
 [ 907 1017  701]
 [ 561  391  595]]
